name: host_app
description: A server app using shelf to serve static files.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
